// Renders a Coordination Brief as a downloadable PDF, styled like the rest of GridSync: an
// inset sheet border, an ink title block, a redline score (the one number this document is
// actually about), and small square markers on section headings echoing the corner-bracket
// dividers used in OpportunityDetail.tsx. jsPDF runs entirely client-side - no server, no
// external service - and buildBrief() is the same data both this and the plain-text copy read,
// so the PDF and the on-screen brief can never say different things.
import { jsPDF } from "jspdf";
import type { Opportunity } from "./types";
import { buildBrief } from "./brief";

const INK: [number, number, number] = [27, 34, 48];
const GRAPHITE: [number, number, number] = [91, 100, 114];
const RULE: [number, number, number] = [201, 206, 198];
const REDLINE: [number, number, number] = [200, 53, 43];

const PAGE_W = 612; // US Letter, points
const PAGE_H = 792;
const MARGIN = 56;
const INSET = 16; // sheet border sits this far outside the text margin
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 13;

function drawSheetBorder(doc: jsPDF) {
  doc.setDrawColor(...INK);
  doc.setLineWidth(1);
  doc.rect(MARGIN - INSET, MARGIN - INSET, PAGE_W - (MARGIN - INSET) * 2, PAGE_H - (MARGIN - INSET) * 2);
}

export function downloadCoordinationBriefPdf(o: Opportunity): void {
  const brief = buildBrief(o);
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  let y = MARGIN;

  const newPage = () => {
    doc.addPage();
    drawSheetBorder(doc);
    y = MARGIN;
  };
  const ensureRoom = (need: number) => {
    if (y + need > PAGE_H - MARGIN) newPage();
  };

  drawSheetBorder(doc);

  // Title block
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...INK);
  doc.text("GridSync", MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...GRAPHITE);
  doc.text("Coordination Brief", MARGIN, y + 15);
  doc.text(
    `Generated ${new Date().toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}`,
    PAGE_W - MARGIN,
    y,
    { align: "right" },
  );
  y += 28;
  doc.setDrawColor(...INK);
  doc.setLineWidth(1.2);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 24;

  // Opportunity + score
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAPHITE);
  doc.text("OPPORTUNITY", MARGIN, y);
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...INK);
  const titleLines = doc.splitTextToSize(brief.title, CONTENT_W);
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 17 + 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAPHITE);
  doc.text("COORDINATION SCORE", MARGIN, y);
  y += 20;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(...REDLINE);
  const scoreNumber = brief.score.split("/")[0];
  doc.text(scoreNumber, MARGIN, y);
  const numberWidth = doc.getTextWidth(scoreNumber);
  doc.setFontSize(13);
  doc.setTextColor(...GRAPHITE);
  doc.text(" / 100", MARGIN + numberWidth, y);
  const rest = brief.score.replace(/^\d+\/100\s*/, "");
  if (rest) {
    doc.setFontSize(10);
    doc.text(rest, MARGIN, y + 16);
    y += 16;
  }
  y += 26;

  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.75);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 22;

  // Sections
  for (const section of brief.sections) {
    ensureRoom(LINE_H * 2 + 10);
    doc.setFillColor(...INK);
    doc.rect(MARGIN, y - 8, 6, 6, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...INK);
    doc.text(section.heading, MARGIN + 12, y);
    y += LINE_H + 4;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...INK);
    for (const raw of section.lines) {
      const wrapped: string[] = doc.splitTextToSize(raw, CONTENT_W - 12);
      for (const line of wrapped) {
        ensureRoom(LINE_H);
        doc.text(line, MARGIN + 12, y);
        y += LINE_H;
      }
    }
    y += 14;
  }

  ensureRoom(LINE_H * 2 + 10);
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.75);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 18;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(...GRAPHITE);
  doc.text("Generated by GridSync. Potential coordination opportunity for planner investigation.", MARGIN, y);

  const safe = (id: string) => id.replace(/[^a-z0-9-]+/gi, "-");
  doc.save(`gridsync-brief-${safe(o.project_a.id)}-${safe(o.project_b.id)}.pdf`);
}
