// The frontend's own internal contract. Originally mirrored analyze_projects() in
// analysis/pipeline.py field for field, but the real backend reshapes that data into its
// own field names (see lib/api.ts's mapAnalyzeResponse()) — so this file now stays fixed and
// the adapter absorbs whatever the backend calls things. Every number here is computed by
// the analysis pipeline; the frontend only displays it.

export type Confidence = "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN";
export type Potential = "HIGH" | "MEDIUM" | "LOW";

// Only the citations a project actually has are present — Duke and TECO cite different things.
export interface ProjectSources {
  project_source?: string;
  source_url?: string;
  geography_source?: string;
  circuit_endpoint_source?: string;
  form1_schedule?: string;
}

export interface Project {
  id: string;
  utility: string;
  name: string;
  project_type: string;
  status: string | null;
  voltage_label: string | null; // as filed, e.g. "138/230 kV"
  start: string | null; // ISO date; null when only a year is known
  end: string | null;
  in_service_year: number | null;
  date_precision: "month" | "year" | null;
  // Representative point (corridor midpoint or substation) + corridor endpoints.
  mid_lat: number | null;
  mid_lon: number | null;
  from_lat: number | null;
  from_lon: number | null;
  to_lat: number | null;
  to_lon: number | null;
  // A straight line between endpoints is an approximate corridor, never the physical route.
  geometry_type: "approximate_corridor" | "point" | null;
  location_confidence: Confidence | null;
  sources: ProjectSources;
}

export interface Analysis {
  distance_miles: number | null; // minimum distance between known endpoints
  geography_available: boolean;
  schedule_overlap_months: number | null; // null unless both sides have month-level dates
  temporal_precision: string | null; // "month" | "mixed" | "unknown"
  year_difference: number | null;
  same_active_year: boolean | null;
  // Score components, 0–100 (null = not available, treated as neutral by the score)
  geographic_score: number | null;
  temporal_score: number | null;
  text_similarity_score: number | null;
  infrastructure_similarity: number | null;
  coordination_score: number; // 0–100
  score_confidence: Confidence | null;
  opportunity_rank: number;
}

export interface SharedResource {
  resource_id: string;
  display_name: string;
  potential: Potential;
  evidence: string[];
}

export interface Opportunity {
  opportunity_id: string;
  project_a: Project; // always Duke
  project_b: Project; // always TECO
  analysis: Analysis;
  evidence: string[]; // "why this matched", generated by the pipeline
  potential_shared_resources: SharedResource[];
  data_confidence: {
    geography: Confidence | null;
    temporal: string | null;
    similarity: Confidence | null;
    overall_score: Confidence | null;
  };
}

export interface AnalyzeSummary {
  utilities: string[];
  projects_analyzed: number;
  pairs_analyzed: number;
  eligible_opportunities: number;
  opportunities_returned: number;
}

export interface AnalyzeResponse {
  summary: AnalyzeSummary;
  opportunities: Opportunity[]; // already in rank order
}

export interface AnalyzeRequest {
  utility_a: string;
  utility_b: string;
}
